### ISSUE TITLE
homebridge integration

### ISSUE THREAD

**Issue by matbe81** [jvandenaardweg/homewizard-energy-api#76]
Any plan to integrate it with homebridge?
What about watermeter HWE-WTR (https://homewizard-energy-api.readthedocs.io/endpoints.html#example-hwe-wtr) ?

**Comment by jvandenaardweg** [comment]
Hi @matbe81 , this API package is just a way to easily interact with the Homewizard API's. Homebridge packages can include this package, but on itself it's not something that can be made into a Homebridge plugin.

For example, my Homebridge Energy Socket plugin uses this API package internally: https://github.com/jvandenaardweg/homebridge-homewizard-energy-socket

**Comment by matbe81** [comment]
I understand this very well.
Can you make a homebridge plugin for the others endpoints of the homewizard API and especially for the watermeter device (simpler)?

**Comment by jvandenaardweg** [comment]
Just commented on that request here: https://github.com/jvandenaardweg/homebridge-homewizard-energy-socket/issues/81
